
--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as Total_Revenue 
FROM customer
Group By gender


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount 
From customer
where discount_applied= 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average Product Rating"
From customer
group by item_purchased
order by avg(review_rating) DESC
limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type, ROUND(AVG(purchase_amount::numeric),2)
From Customer
where shipping_type in ('Standard','Express')
Group BY shipping_type


--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

select subscription_status, COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount::numeric),2) as avg_spend,
ROUND(SUM(purchase_amount::numeric),2) as total_revenue
From customer
Group by subscription_status
order by total_revenue, avg_spend


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
100*SUM(Case when discount_applied='Yes' THEN 1 Else 0 END)/Count(item_purchased) as discount_rate
From Customer
Group by item_purchased
order by discount_rate DESC
Limit 5


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
WITH Customer_type as(
select customer_id, previous_purchases,
CASE
     WHEN previous_purchases= 1 THEN 'NEW'
     WHEN previous_purchases BETWEEN 2 AND 10 THEN 'RETURNING'
	 ELSE 'LOYAL'
	 END AS Customer_segment
FROM Customer
)
select customer_Segment, count(*) from Customer_type
Group by customer_Segment

--Q8. What are the top 3 most purchased products within each category? 

WITH item_counts as(
Select category,item_purchased, Count(customer_id) as total_orders,
ROW_NUMBER() OVER(Partition By Category order by count(customer_id) DESC) as item_rank
from customer
group by category,item_purchased
)
Select * from item_counts
where item_rank<=3

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select count(customer_id) as repeat_buyers,subscription_status 
from customer
where previous_purchases >5
group by subscription_status


--Q10. What is the revenue contribution of each age group? 
Select age_group, sum(purchase_amount) as "Total Revenue"
From Customer
Group by age_group
order by "Total Revenue" DESC